### ISSUE TITLE
。。

### ISSUE THREAD

**Issue by wangtianshang** [ronething/Scrapy-build-a-SearchEngines#1]
你好，你有这个慕课网的资源吗？可以让我看看吗，直接看代码有点费劲，看不太懂

**Comment by ronething** [comment]
> 你好，你有这个慕课网的资源吗？可以让我看看吗，直接看代码有点费劲，看不太懂

https://github.com/mtianyan/FunpySpiderSearchEngine

有其他人也学习了这个项目。他的readme很详细。也有教程。你可以了解一下。

**Comment by wangtianshang** [comment]
谢谢 在2018年12月02日 12:25 ，ronething写道： 你好，你有这个慕课网的资源吗？可以让我看看吗，直接看代码有点费劲，看不太懂 https://github.com/mtianyan/FunpySpiderSearchEngine 有其他人也学习了这个项目。他的readme很详细。也有教程。你可以了解一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
